### ISSUE TITLE
As a user, I want to let my cell phone's camera detect morse code, in order to get the translation on my screen when some morses to me.

### ISSUE THREAD

**Issue by aruppert** [TARE2020/morsemouse#10]
### Criteria

- [ ] app can detect morse code with camera in total darkness
- [ ] app gives translation of detected code
- [ ] when code repeats (e.g. 50% identical with already logged code), app switches automatically to translation

### To-Dos

- [ ] research how to access camera and detect a flashing light and the length of the flash
- [ ] create function which stores the detected code
- [ ] create function which recognises repetition to show code automatically
