### ISSUE TITLE
As a user, I want to morsemouse to display my GPS coordinates on screen, when I use the SOS-function, in order to get help.

### ISSUE THREAD

**Issue by aruppert** [TARE2020/morsemouse#11]
### Criteria

- [ ] after clicking the SOS-button, current GPS coordinates of the device/user are displayed 

### To-Dos

- [ ] create emergency page 
- [ ] display GPS coordinates in an easy to read fashion
