### ISSUE TITLE
As a user, I want to have two text areas, in order to see my input (usually text) and the morse code translation.

### ISSUE THREAD

**Issue by aruppert** [TARE2020/morsemouse#5]
### Criteria

- [x] two text areas on page
- [x] functionality of translating text to code
- [x] functionality of translating code to text

### To-Dos

- [x] create two text areas with labels
- [x] build translation functionality text to code
- [x] build translation functionality code to text
