### ISSUE TITLE
As a user, I want to 'play' the morse code with the flash light of my cell phone, in order to communicate in dangerous situations.

### ISSUE THREAD

**Issue by aruppert** [TARE2020/morsemouse#6]
### Criteria

- [ ] have a button on the page to start 'playback' with flash light
- [ ] let light flash according to translated text (morse code)
- [ ] repeat the code infinitely

### To-Dos

- [ ] create button(s; one for start and one for stop/loop)
- [ ] access cell phones flash light and playback code
- [ ] research standard length of . and - in ms
- [ ] create funcitionality
