### ISSUE TITLE
As a user, I want to have a SOS button with preset SOS morse code, in order to morse easily when in great danger.

### ISSUE THREAD

**Issue by aruppert** [TARE2020/morsemouse#7]
### Criteria

- [x] have a easy accessable SOS-button for emergency use

### To-Dos

- [x] create styled button
- [ ] preset code to SOS and start a playback loop without any further actions
