### ISSUE TITLE
As a developer, I want to setup my fresh mac, in order to be able to host our pair programming sessions as well.

### ISSUE THREAD

**Issue by aruppert** [TARE2020/morsemouse#8]
### Criteria

- [x] have a  nicely running mac like in the bootcamp

### To-Dos

- [x]  install all necessary software to code and pair program
- [ ] setup new mac with my preferences
